let country_list = {
    "United Arab Emirates (AED)":"AE",
    "Afghanistan (AFN)":"AF",
    "Antigua and Barbuda (XCD)": "AG",
    "Albania (ALL)": "AL",
    "Armenia (AMD)": "AM",
    "Netherlands Antilles (ANG)": "AN",
    "Angola (AOA)": "AO",
    "Antarctica (AQD)": "AQ",
    "Argentina (ARS)": "AR",
    "Australia (AUD)": "AU",
    "Azerbaijan (AZN)": "AZ",
    "Bosnia and Herzegovina (BAM)": "BA",
    "Barbados (BBD)": "BB",
    "Bangladesh (BDT)": "BD",
    "Benin (XOF)": "BE",
    "Bulgaria (BGN)": "BG",
    "Bahrain (BHD)": "BH",
    "Burundi (BIF)": "BI",
    "Bermuda (BMD)": "BM",
    "Brunei (BND)": "BN",
    "Bolivia (BOB)": "BO",
    "Brazil (BRL)": "BR",
    "Bahamas (BSD)": "BS",
    "Bouvet Island (NOK)": "BV",
    "Botswana (BWP)": "BW",
    "Belarus (BYR)": "BY",
    "Belize (BZD)": "BZ",
    "Canada (CAD)": "CA",
    "Congo (Kinshasa) (CDF)": "CD",
    "Central African Republic (XAF)": "CF",
    "Switzerland (CHF)": "CH",
    "Chile (CLP)": "CL",
    "China (CNY)": "CN",
    "Colombia (COP)": "CO",
    "Costa Rica (CRC)": "CR",
    "Cuba (CUP)": "CU",
    "Cape Verde (CVE)": "CV",
    "Cyprus (CYP)": "CY",
    "Czech Republic (CZK)": "CZ",
    "Djibouti (DJF)": "DJ",
    "Denmark (DKK)": "DK",
    "Dominican Republic (DOP)": "DO",
    "Algeria (DZD)": "DZ",
    "Ecuador (ECS)": "EC",
    "Estonia (EEK)": "EE",
    "Egypt (EGP)": "EG",
    "Ethiopia (ETB)": "ET",
    "France (EUR)": "FR",
    "Fiji (FJD)": "FJ",
    "Falkland Islands (FKP)": "FK",
    "United Kingdom (GBP)": "GB",
    "Georgia (GEL)": "GE",
    "Guernsey (GGP)": "GG",
    "Ghana (GHS)": "GH",
    "Gibraltar (GIP)": "GI",
    "Gambia (GMD)": "GM",
    "Guinea (GNF)": "GN",
    "Guatemala (GTQ)": "GT",
    "Guyana (GYD)": "GY",
    "Hong Kong (HKD)": "HK",
    "Honduras (HNL)": "HN",
    "Croatia (HRK)": "HR",
    "Haiti (HTG)": "HT",
    "Hungary (HUF)": "HU",
    "Indonesia (IDR)": "ID",
    "Israel (ILS)": "IL",
    "India (INR)":"IN",
    "Iraq (IQD)": "IQ",
    "Iran (IRR)": "IR",
    "Iceland (ISK)": "IS",
    "Jamaica (JMD)": "JM",
    "Jordan (JOD)": "JO",
    "Japan (JPY)": "JP",
    "Kenya (KES)": "KE",
    "Kyrgyzstan (KGS)": "KG",
    "Cambodia (KHR)": "KH",
    "Comoros (KMF)": "KM",
    "North Korea (KPW)": "KP",
    "South Korea (KRW)": "KR",
    "Kuwait (KWD)": "KW",
    "Cayman Islands (KYD)": "KY",
    "Kazakhstan (KZT)": "KZ",
    "Laos (LAK)": "LA",
    "Lebanon (LBP)": "LB",
    "Sri Lanka (LKR)": "LK",
    "Liberia (LRD)": "LR",
    "Lesotho (LSL)": "LS",
    "Lithuania (LTL)": "LT",
    "Latvia (LVL)": "LV",
    "Libya (LYD)": "LY",
    "Morocco (MAD)": "MA",
    "Moldova (MDL)": "MD",
    "Madagascar (MGA)": "MG",
    "North Macedonia (MKD)": "MK",
    "Myanmar (MMK)": "MM",
    "Mongolia (MNT)": "MN",
    "Macau (MOP)": "MO",
    "Mauritania (MRO)": "MR",
    "Malta (MTL)": "MT",
    "Mauritius (MUR)": "MU",
    "Maldives (MVR)": "MV",
    "Malawi (MWK)": "MW",
    "Mexico (MXN)": "MX",
    "Malaysia (MYR)": "MY",
    "Mozambique (MZN)": "MZ",
    "Namibia (NAD)": "NA",
    "New Caledonia (XPF)": "NC",
    "Nigeria (NGN)": "NG",
    "Nicaragua (NIO)": "NI",
    "Nepal (NPR)": "NP",
    "New Zealand (NZD)": "NZ",
    "Oman (OMR)": "OM",
    "Panama (PAB)": "PA",
    "Peru (PEN)": "PE",
    "Papua New Guinea (PGK)": "PG",
    "Philippines (PHP)": "PH",
    "Pakistan (PKR)": "PK",
    "Poland (PLN)": "PL",
    "Paraguay (PYG)": "PY",
    "Qatar (QAR)": "QA",
    "Romania (RON)": "RO",
    "Serbia (RSD)": "RS",
    "Russia (RUB)": "RU",
    "Rwanda (RWF)": "RW",
    "Saudi Arabia (SAR)": "SA",
    "Solomon Islands (SBD)": "SB",
    "Seychelles (SCR)": "SC",
    "Sudan (SDG)": "SD",
    "Sweden (SEK)": "SE",
    "Singapore (SGD)": "SG",
    "Slovakia (SKK)": "SK",
    "Sierra Leone (SLL)": "SL",
    "Somalia (SOS)": "SO",
    "Suriname (SRD)": "SR",
    "Sao Tome and Principe (STD)": "ST",
    "El Salvador (SVC)": "SV",
    "Syria (SYP)": "SY",
    "Eswatini (SZL)": "SZ",
    "Thailand (THB)": "TH",
    "Tajikistan (TJS)": "TJ",
    "Turkmenistan (TMT)": "TM",
    "Tunisia (TND)": "TN",
    "Tonga (TOP)": "TO",
    "Turkey (TRY)": "TR",
    "Trinidad and Tobago (TTD)": "TT",
    "Taiwan (TWD)": "TW",
    "Tanzania (TZS)": "TZ",
    "Ukraine (UAH)": "UA",
    "Uganda (UGX)": "UG",
    "United States (USD)":"US",
    "Uruguay (UYU)": "UY",
    "Uzbekistan (UZS)": "UZ",
    "Venezuela (VEF)": "VE",
    "Vietnam (VND)": "VN",
    "Vanuatu (VUV)": "VU",
    "Yemen (YER)": "YE",
    "South Africa (ZAR)": "ZA",
    "Zambia (ZMK)": "ZM",
    "Zimbabwe (ZWD)": "ZW",
};
